name: github pages

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: enable corepack
        run: corepack enable

      - name: install packages
        run: pnpm install
        
      - name: build
        run: pnpm build-storybook
        env:
          BUILD_BASE_URL: /jsonforms-antdv/
