name: component-testing
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [15]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
      - name: pnpm Build
        run: pnpm install
      # On the first run, the tests often fail, probably due to the build, so run the test twice.
      - name: "Cypress component testing: Warm up"
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        continue-on-error: true
        with:
          install: false
          command: pnpm test
      - name: "Cypress component testing: Run"
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        # The second running test failure stops ci.
        continue-on-error: false
        with:
          install: false
          command: pnpm test
