name: component-testing
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
          run_install: true

      # Flaky test, run test twice. 
      - name: "Cypress component testing: Warm up"
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        continue-on-error: true
        with:
          install: false
          command: pnpm test

      - name: "Cypress component testing: Run"
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        # The second running test failure stops ci.
        continue-on-error: false
        with:
          install: false
          command: pnpm test
