name: component-testing
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: enable corepack
        run: corepack enable

      - name: install packages
        run: pnpm install
        
      # Flaky test, run test twice. 
      - name: "Cypress component testing: Warm up"
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        continue-on-error: true
        with:
          install: false
          command: pnpm test

      - name: "Cypress component testing: Run"
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        # The second running test failure stops ci.
        continue-on-error: false
        with:
          install: false
          command: pnpm test
