name: github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: enable corepack
        run: corepack enable

      - name: install packages
        run: pnpm install

      - name: build
        run: pnpm build-storybook
        env:
          BUILD_BASE_URL: /jsonforms-antdv/

      - name: nojekyll
        run: touch storybook-static/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: storybook-static
